version: 2.0

scenario_matrix:
  model_file: ["spd_test"]
  regions: [1-supply] #, 11-supply]
  resarea: [redz]
  ll: ["copt"]
  opts: [LC]

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

# General inputs
data:
  resarea:
    redz: REDZ_DEA_Unpublished_Draft_2015
    corridors: Power_corridors

# definition of the Coordinate Reference Systems
crs:
  geo_crs: EPSG:4326  # general geographic projection, not used for metric measures. "EPSG:4326" is the standard used by OSM and google maps
  distance_crs: EPSG:2049 # projection for distance measurements only. Possible recommended values are "EPSG:3857" (used by OSM and Google Maps)
  area_crs: ESRI:54009  # projection for area measurements only. Possible recommended values are Global Mollweide "ESRI:54009"

# When running the model for the first time it is necessary to enable the following scripts:
# build_natura_raster, build_population, build_topology, build_cutout. For subsequent model
# runs these scripts can be diabled to save time. Although snakemake will skip the execution
# of scripts where the outputs are already built, these switches are useful for forced 
# re-runs of the snakemake workflow, where you may not necessarily want to rebuild everything
enable:
  build_natura_raster: false # Rasters natural protection areas onto all cutout regions
  build_topology: true # Base network topology
  build_cutout: false #false # Atlite cutout 
  use_eskom_wind_solar: false # Model defaults to Eskom hourly pu profiles for all wind and solar generators
  use_excel_wind_solar: [true,"../data/wind_solar_profiles.xlsx"] # Model defaults to excel input hourly pu profiles for all wind and solar generators  
  build_renewable_profiles: false #false # Enable calculation of renewable profiles

# Specification of relevent years for the model
years: 
  reference_demand_year: 2017  # should be a single year at present, could be extended in the future
  reference_weather_years: 
    # reference years used for solar PV and wind profiles - can be single or multiple years
    # if multiple years are specified these are applied sequencially to the simulation years
    solar_pv: [2012]
    wind: [2012, 2013]

    # reference years from actual Eskom data published at https://www.eskom.co.za/dataportal/ 
    # can be single or multiple years if multiple years are specified these are applied 
    # sequencially to the simulation years
    solar_csp: [2021] 
    biomass: [2021]
    hydro: [2021]
    hydro_import: [2021]

electricity:
  demand_disaggregation: "GVA2016" # used to split the demand across supply regions in absence of Eskom data 
  co2limit: 2.2e+9    # Cumulative CO2 emissions budget for all simulation years combined
  renewable_generators:
    carriers: [wind, solar_pv, solar_csp, biomass, hydro, hydro_import] # defines renewable carriers
    apply_grouping: true # if false indivudal plants are specified as generators
  #renewable_carriers: [solar_pv, wind, solar_csp, biomass, hydro, hydro_import] # defines renewable carriers
  #group_ipp_generators: true # group IPPs by keyword in model_file
  conventional_generators: # generator planned and unplanned outages are included based on Eskom data
    carriers: ["coal", "ocgt_diesel", "ocgt_gas", "ccgt_steam", "nuclear", hydro, hydro_import, "sasol_coal", "sasol_gas"]
    apply_grouping: false # if false indivudal plants are specified as generators
    implement_availability: true
    fix_ref_years: [2019] #if multiple years specified an average is used
    ext_ref_years: [2017] #if multiple years specified an average is used
    
    extendable_reference: 
    # New generator availability is based on an existing Eskom generator
      coal: "Lethabo"
      ocgt_diesel: "Ankerlig"
      ocgt_gas: "Ankerlig"
      ccgt_steam: "Ankerlig"
      nuclear: "Koeberg"
      hydro: "Gariep"
      #hydro_import: "Cahora Bassa"

  ccgt_gt_to_st_ratio: 0.3 # ratio of gas turbines to steam turbines in CCGT plants

  extendable_parameters:
    defaults:
      discount_rate: 0.082
      co2_emissions: 0
      FOM: 0
      VOM: 0
      heat_rate: 0
      efficiency: 1
      fuel: 0
      investment: 0
      lifetime: 20
      min_stable_level: 0

  adjust_by_p_max_pu: #adjusts ramp limit and p_min_pu by outages representated by p_max_pu
    coal: [ramp_limit_up, ramp_limit_down]
    nuclear: [ramp_limit_up, ramp_limit_down, p_min_pu] # leave empty to ignore
  
  # minimum station hourly generation % of p_nom
  # useful for avoiding unrealistic coal fleet operation in capacity expansion plan without unit committment
  min_hourly_station_gen: 
    fixed:
      coal: 0.3 # assume 1 unit at part load
    extendable:
      coal: 0.3 # assume 1 unit at part load

  reserves:
    capacity_credit:
      coal: 0.8
      ocgt_gas: 1
      ocgt_diesel: 1
      ccgt_steam: 1
      biomass: 1
      wind: 0.1 #.i.e only 10% of installed wind capacity is counted towards reserve_margin
      phs: 1
      battery: 0.5
      nuclear: 1

    operating_reserves:
        spinning: ["coal", "nuclear", "phs", "biomass", "hydro", "hydro_import"]
        non_spinning: ["coal", "ocgt_diesel", "ocgt_gas", "ccgt_gas", "phs", "biomass", "hydro", "hydro_import"]
  
  dispatch_committable_carriers:
    existing: [coal]
    extended: [coal, ccgt_steam]
  
respotentials:
  # Gives us ball-park the available areas the IWES study reports
  landusetype_percent:
  # grid codes
    wind:
      - [[7, 8, 9, 41], 80]
      # - [[5, 6], 50]
      # - [[11, 12, 14, 15], 10]
    solar_pv:
      - [[7, 8, 9, 41], 80]
      # - [[11, 12, 14, 15], 50]
      # - [[46, 47, 51, 56, 64, 68, 72], 10]

  capacity_per_sqm:
    wind: 5   # half of 10 (IWES)
    solar_pv: 16.5 # half of 33 (IWES)

atlite:
  cutout_snapshots:
    start: "2017-01-01"
    end: "2018-01-01"
    #closed: "left" # end is not inclusive
  nprocesses: 10
  cutouts:
    RSA-2017_20-era5:
      module: era5 # in priority order
      x: [16, 35]
      y: [-35., -21]
      dx: 0.3
      dy: 0.3
      time: ["2017","2017"]
    # RSA-2012-sarah:
    #  module: [sarah, era5] # in priority order
    #  x: [16, 35]
    #  y: [-35.,-21]
    #  dx: 0.2
    #  dy: 0.2
    #  time: ["2012", "2012"]
    #  sarah_interpolate: false
    #  sarah_dir:
    #  features: [influx, temperature]
  apply_wind_correction: true

renewable:
  wind:
    cutout: RSA-2017_20-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_4MW
    capacity_per_sqkm: 3 # ScholzPhd Tab 4.3.1: 10MW/km^2 and assuming 30% fraction of the already restricted
    # area is available for installation of wind generators due to competing land use and likely public
    # acceptance issues.
    # correction_factor: 0.93
    salandcover:
      grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]

    #corine:
      # Scholz, Y. (2012). Renewable energy based electricity supply at low costs:
      #  development of the REMix model and application for Europe. ( p.42 / p.28)
    #  grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32]
    #  distance: 1000
    #  distance_grid_codes: [1, 2, 3, 4, 5, 6]
    natura: true
    excluder_resolution: 100
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2

  solar_pv:
    cutout: RSA-2017_20-era5
    resource:
      method: pv
      panel: CSi
      orientation: latitude_optimal
        #slope: 35.
        #azimuth: 0.
    capacity_per_sqkm: 1.7 # ScholzPhd Tab 4.3.1: 170 MW/km^2 and assuming 1% of the area can be used for solar PV panels
    # Correction factor determined by comparing uncorrected area-weighted full-load hours to those
    # published in Supplementary Data to
    # Pietzcker, Robert Carl, et al. "Using the sun to decarbonize the power
    # sector: The economic potential of photovoltaics and concentrating solar
    # power." Applied Energy 135 (2014): 704-720.
    # This correction factor of 0.854337 may be in order if using reanalysis data.
    # for discussion refer to https://github.com/PyPSA/pypsa-eur/pull/304
    # correction_factor: 0.854337
  #  corine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 26, 31, 32]
    natura: true
    excluder_resolution: 100
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
    salandcover:
      grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]
  # hydro:
  #   cutout: RSA-2013-era5
  #   carriers: [ror, PHS, hydro]
  #   PHS_max_hours: 6
  #   hydro_max_hours: "energy_capacity_totals_by_country" # one of energy_capacity_totals_by_country, estimate_by_large_installations or a float
  #   clip_min_inflow: 1.0

hydro_inflow:
  disable: false #true
  source: eskom #or calculate runoff using atlite
  countries: [ZA, MZ] # only applicable to atlite
  cutout: za-mz-2012 # only applicable to atlite

lines:
  threshold: 220 # only voltages >=220kV are considered in network capacity calculations
  v_nom: 400. #changed from 380kV from PyPSA-EUR to 400kV for South Africa
  type: 
    400: "Al/St 240/40 4-bundle 380.0" # proxy line properties from pypsa defaults
  s_rating:  thermal # thermal, SIL, StClair
  thermal:
    220: 492  #(MW) "Al/St 240/40 2-bundle 220.0" -> np.sqrt(3)*220*1.29
    275: 921  #(MW) "Al/St 240/40 3-bundle 300.0" -> np.sqrt(3)*275*1.935
    400: 1788 #(MW) "Al/St 240/40 4-bundle 380.0" -> np.sqrt(3)*400*2.58
    765: 5512 #(MW) "Al/St 560/50 4-bundle 750.0" -> np.sqrt(3)*765*4.16
  SIL: # surge impedance loading
    220: 122  #(MW) 
    275: 245  #(MW) 
    400: 602  #(MW) 
    765: 2280 #(MW) 
  s_max_pu: 0.7 # n-1 approximation
  s_nom_max: .inf
  length_factor: 1.25
  dc_type: "DC_custom_linetype"
  status: ["existing"] # "zero": set capacity to zero, "remove": remove, "keep": with full capacity
  extend_topology: true # if true, lines between adjacent regions that do not exist are added for expansion

links:
  p_max_pu: 1.0
  p_nom_max: .inf
  under_construction: "zero" # "zero": set capacity to zero, "remove": remove, "keep": with full capacity
  length_factor: 1.25

costs:
  # costs come from data/technology_costs.xlsx
  discount_rate: 0.082
  year: 2030
  USD_to_ZAR: 18.24
  EUR_to_ZAR: 17.83

  load_shedding: 100000 #R100/kWh

  emission_prices: # only used with the option Ep (emission prices)
    # Externality costs from Integrated Energy Plan by the ZA DOE
    co2: 0.27e+3
    sox: 7.6e+3
    nox: 4.5e+3
    hg: 41484.e-6 # is also part of the excel sheet
    particulate: 11.3e+3

tsam_clustering:
  nprocesses: 10
  solver: "cbc" #need to use open source solver here due to parallel processing of years
 

solving:
  tmpdir: /tmp
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    skip_iterations: false
    min_iterations: 1
    max_iterations: 10
    msq_threshold: 0.05 # mean squared error threshold for convergence of iterations
    formulation: kirchhoff
    warmstart: false
    # max_iterations: 1
    # nhours: 10
  solver:
    name: xpress
    lpflags: 4
    crossover: 0
    bargapstop: 1.e-5
    barstart: -1 #use xpress warmstart
    #baralg: 2 
    #barstartweight: 1
    # FeasibilityTol: 1.e-6
    # LogToConsole: 0
    # OutputFlag: 1

plotting:
  map:
    figsize: [10, 10]
    boundaries: [14, 34, -35, -22] #[x1,x2,y1,y2]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3 #1.e+3 # 1.e+3  #3.e+3

  costs_max: 1000

  vre_techs: ["wind","solar_pv", "hydro", "hydro_import"]
  conv_techs: ["ocgt_diesel", "ocgt_gas", "ccgt_gas", "nuclear", "coal"]
  storage_techs: ["hydro", "CAES", "battery", "PHS", "hydro+PHS"]
  store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load", "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"] 
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    "wind": "#77D1E4"
    "onshore wind": "#77D1E4"
    "offwind": "#77D1E4"
    "offwind-ac": "#77D1E4"
    "offshore wind": "#77D1E4"
    "offshore wind ac": "#77D1E4"
    "offwind-dc": "#77D1E4"
    "offshore wind dc": "#77D1E4"
    "hydro": "#004F95"
    "hydro_import": "#004F95"
    "hydro+PHS": "#004F95"
    "PHS": "#004F95"
    "hydro reservoir": "#004F95"
    "hydroelectricity": "#004F95"
    "ror": "#4adbc8"
    "run of river": "#4adbc8"
    "solar": "#FFBB4E"
    "solar PV": "#FFBB4E"
    "solar_csp": "#FEED82"
    "biomass": "#0c6013"
    "solid biomass": "#06540d"
    "biogas": "#23932d"
    "waste": "#68896b"
    "geothermal": "#ba91b1"
    "OCGT": "#8D7867"
    "gas": "#d35050"
    "natural gas": "#d35050"
    "CCGT": "#CCC8C8"
    "nuclear": "#C84936"
    "coal": "#3C3C3C"
    "lignite": "#9e5a01"
    "diesel": "#262626"
    "H2": "#ea048a"
    "hydrogen storage": "#ea048a"
    "battery": "#AA68AA"
    "Electric load": "#f9d002"
    "electricity": "#f9d002"
    "lines": "#70af1d"
    "transmission lines": "#70af1d"
    "AC-AC": "#70af1d"
    "AC line": "#3C3C3C"
    "links": "#8a1caf"
    "HVDC links": "#8a1caf"
    "DC-DC": "#8a1caf"
    "DC link": "#8a1caf"
    "load_shedding": "#FF0000"
    "Load": "#FF0000"
  nice_names:
    OCGT: "OCGT" #"Open-Cycle Gas"
    CCGT: "CCGT" #"Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    wind: "Wind"
    solar: "PV"
    phs: "Pumped Hydro Storage"
    hydro: "Hydro"
    hydro+PHS: "Hydro+PS"
    battery: "Battery"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
    coal: "Coal"
    nuclear: "Nuclear"
    biomass: "Biomass"